backend:
  name: git-gateway
  branch: master

local_backend: true

publish_mode: editorial_workflow

media_folder: "static/img"

public_folder: "/img"

site_url: https://confident-euler-cf03d1.netlify.app/

display_url: https://confident-euler-cf03d1.netlify.app/

locale: 'ja'

collections:
  - name: "article"
    label: "記事作成"
    folder: "src/pages/articles"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "テンプレートキー", name: "templateKey", widget: "hidden", default: "blog-post" }
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "特集記事(3記事まで表示可能)", name: "featured", widget: "boolean", default: false }
      - { label: "説明(特集記事の場合は必須)", name: "description", widget: "text", required: false }
      - { label: "カテゴリー", name: "categories", widget: "select", options: ["ARTS", "GADGETS", "BUSINESS", "NOVELS", "MOVIES", "CULTURE"], multiple: true, default: ["BUSINESS"], min: 1 }
      - { label: "タグ", name: "tags", widget: "list" }
      - { label: "見出し画像", name: "featuredimage", widget: "file", allow_multiple: false }
      - { label: "公開日", name: "issuedAt", widget: "datetime" }
      - { label: "本文", name: "body", widget: "markdown" }
